# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dc_net.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dc_net.proto',
  package='DCnet',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0c\x64\x63_net.proto\x12\x05\x44\x43net\"\x92\x01\n\x06\x44\x43_net\x12\x19\n\x11\x64\x63_net_identifier\x18\x01 \x02(\x05\x12\x19\n\x11\x63lient_identifier\x18\x02 \x02(\x05\x12\x17\n\x0ftransmissionBit\x18\x03 \x01(\x05\x12\x11\n\ttimestamp\x18\x04 \x02(\t\x12\x14\n\x0cnotification\x18\x05 \x01(\x05\x12\x10\n\x08localSum\x18\x06 \x02(\x05\"$\n\x0b\x41\x63knowlegde\x12\x15\n\rMessageStatus\x18\x01 \x01(\x05\"&\n\tDC_Client\x12\x19\n\x11\x63lient_identifier\x18\x01 \x01(\x05\x32>\n\x08\x44\x43_round\x12\x32\n\x0bGetLocalSum\x12\r.DCnet.DC_net\x1a\x12.DCnet.Acknowlegde\"\x00'
)




_DC_NET = _descriptor.Descriptor(
  name='DC_net',
  full_name='DCnet.DC_net',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='dc_net_identifier', full_name='DCnet.DC_net.dc_net_identifier', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='client_identifier', full_name='DCnet.DC_net.client_identifier', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='transmissionBit', full_name='DCnet.DC_net.transmissionBit', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='DCnet.DC_net.timestamp', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='notification', full_name='DCnet.DC_net.notification', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='localSum', full_name='DCnet.DC_net.localSum', index=5,
      number=6, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=170,
)


_ACKNOWLEGDE = _descriptor.Descriptor(
  name='Acknowlegde',
  full_name='DCnet.Acknowlegde',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='MessageStatus', full_name='DCnet.Acknowlegde.MessageStatus', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=172,
  serialized_end=208,
)


_DC_CLIENT = _descriptor.Descriptor(
  name='DC_Client',
  full_name='DCnet.DC_Client',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='client_identifier', full_name='DCnet.DC_Client.client_identifier', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=210,
  serialized_end=248,
)

DESCRIPTOR.message_types_by_name['DC_net'] = _DC_NET
DESCRIPTOR.message_types_by_name['Acknowlegde'] = _ACKNOWLEGDE
DESCRIPTOR.message_types_by_name['DC_Client'] = _DC_CLIENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DC_net = _reflection.GeneratedProtocolMessageType('DC_net', (_message.Message,), {
  'DESCRIPTOR' : _DC_NET,
  '__module__' : 'dc_net_pb2'
  # @@protoc_insertion_point(class_scope:DCnet.DC_net)
  })
_sym_db.RegisterMessage(DC_net)

Acknowlegde = _reflection.GeneratedProtocolMessageType('Acknowlegde', (_message.Message,), {
  'DESCRIPTOR' : _ACKNOWLEGDE,
  '__module__' : 'dc_net_pb2'
  # @@protoc_insertion_point(class_scope:DCnet.Acknowlegde)
  })
_sym_db.RegisterMessage(Acknowlegde)

DC_Client = _reflection.GeneratedProtocolMessageType('DC_Client', (_message.Message,), {
  'DESCRIPTOR' : _DC_CLIENT,
  '__module__' : 'dc_net_pb2'
  # @@protoc_insertion_point(class_scope:DCnet.DC_Client)
  })
_sym_db.RegisterMessage(DC_Client)



_DC_ROUND = _descriptor.ServiceDescriptor(
  name='DC_round',
  full_name='DCnet.DC_round',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=250,
  serialized_end=312,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetLocalSum',
    full_name='DCnet.DC_round.GetLocalSum',
    index=0,
    containing_service=None,
    input_type=_DC_NET,
    output_type=_ACKNOWLEGDE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DC_ROUND)

DESCRIPTOR.services_by_name['DC_round'] = _DC_ROUND

# @@protoc_insertion_point(module_scope)
